### ISSUE TITLE
Create users from CSVs

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-conf#61] opened 2018-03-06 16:09 UTC
A csv such as:
```
uuid,chw_name,name,contact.uuid,contact.name,username,password,phone,district,village,parish,subcounty
```
should create a user with the following calls
```
POST /api/v1/people
{
 "imported_date": "2018-03-06T10:16:43.100Z",
 "place": "aaa-111",
 "_id": "bbb-222",
 "name": "Abigail Person",
 "phone": "123456789",
 "type": "person"
}
```
```
POST /api/v1/places
{
 "imported_date": "2018-03-06T10:16:42.930Z",
 "parent": "test_place",
 "_id": "aaa-111",
 "name": "Abigail Person Area",
 "parish": "Bath Spa",
 "village": "Huxbery",
 "district": "Toshingham",
 "type": "health_center"
}
```
```
POST /api/v1/places/bf45f23c-f249-4415-abaf-47bfd56af83b
{
 "contact": "aaa-111"
}
```
It may be possible to eliminate the final call by generating the person UUID before the initial call.

It may also be necessary to create a higher level of place from the names listed in the CSV file.

Note that some fields in the CSV are _required_, but others will be project-specific.

**Comment by alxndrsn** [comment] 2018-03-20 09:17
Why not use https://github.com/medic/medic-webapp/tree/master/api#post-apiv1users?

**Comment by alxndrsn** [comment] 2018-03-21 10:45
@abbyad are you able to test this on a branch?  or would you like it included as an alpha option in the main release?

**Comment by abbyad** [comment] 2018-03-21 13:35
Doing it on a branch is more appropriate, but alpha option is easiest. Is it an isolated enough change to do alpha this time, and we can set up a better testing practice moving forward?

**Comment by alxndrsn** [comment] 2018-03-21 17:37
@abbyad alpha feature released in `v1.11.8`.

**Comment by sglangevin** [comment] 2018-07-11 21:56
@abbyad did any testing of this feature happen? Is more work required? This would be really helpful for tech leads who are still using the old scripts for user creation.

**Comment by garethbowen** [comment] 2018-10-09 19:36
Basically a duplicate of https://github.com/medic/medic-webapp/issues/1709 so removing this from the project and using that instead.

**Comment by garethbowen** [comment] 2019-04-17 12:00
Duplicate.

**Closed by garethbowen** 2019-04-17 12:00 UTC
