### ISSUE TITLE
Warn config overwrite falsely alerts about changes when uploading certain types of attachments

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-conf#345] opened 2020-07-22 11:58 UTC
**Describe the bug**
When uploading files with attachments with medic-conf, you might be prompted for user actions when making no changes. 
This seems to always happen when one attachment is of a text file type: text/plain, text/html, text/javascript etc.

**To Reproduce**
1. Create a new empty "config" folder. 
1. Create a file named `resources.json` and add `{}` as content (nothing else is necessary, but you can also copy the file from `cht-core/config/default`, it makes no difference).
1. Create a folder called "resources"
1. In "resources" folder, create a .txt file. Contents and name irrelevant. 
1. In console, navigate to this config folder and run `medic-conf --local upload-resources`. If you're prompted to overwrite, just do it, first time doesn't matter. 
1. Check the "resources" doc on your instance and confirm it has your text document attachment and that it has the expected contents. 
1. run `medic-conf --local upload-resources` again. 

Notice you're getting the `You are trying to modify a configuration that has been modified since your last upload.` message, even though you have not changed anything. 
Every time you run `medic-conf --local upload-resources`, even if you overwrite every time, you'll get the warning. 

**Expected behavior**
The 2nd and next times we upload without making any changes, we should not get the prompt. 

**Additional context**
It looks like the code we use to "emulate" couchdb digests does not produce correct results when run over text-like documents: 
https://github.com/medic/medic-conf/blob/master/src/lib/warn-upload-overwrite.js#L67

**Comment by dianabarsan** [comment] 2020-07-24 13:26
Slight problem with this one. 

It appears that CouchDB has two settings that determine the compression applied over attachments.
These settings are called `attachments/compressible_types` and `attachments/compression_level`. The default configuration has the following values for these:
```
compression_level = 8 ; from 1 (lowest, fastest) to 9 (highest, slowest), 0 to disable compression
compressible_types = text/*, application/javascript, application/json, application/xml
```
(https://github.com/apache/couchdb/blob/ab93b155095643ab13f3779abc6c948fe273fe4b/rel/overlay/etc/default.ini#L387)

CouchDB applies compression **before** generating the md5 digest, so the outcome is affected directly by these 2 setting values, and compression is applied **by default** over any text file type. 

If I do a `zlib.gzip` with the same `level` of compression as CouchDB, I do indeed get the same digest. 
What do you think, @garethbowen ? Is it worth we schedule this? 
We're introducing HTML attachments with the new privacy policy feature, and every upload of these will falsely warn unless we refine our digest calculation. 

More information here: https://github.com/pouchdb/pouchdb/issues/3156#issuecomment-66831010

**Comment by garethbowen** [comment] 2020-07-26 21:10
I think we need to schedule some sort of fix otherwise it'll annoy app builders and undermine trust in the change detection warning. It doesn't necessarily need to block 3.10.0 because not many people will use the privacy policy right away and we can release a new medic-conf with this fix any time.

There are a few ways to fix it. We could use a different change detection for text docs which downloads the actual attachment rather than relying on the md5. Or we could skip detection on text files altogether.

But I prefer your recommended approach of zipping then hashing. We should add a test which generates the md5 locally and then on the server to ensure if we bump CouchDB and they use a different technique, or we change the default compression config, we detect it and fix it.

Scheduling for 3.11.0 as discussed above - let me know if you disagree!

**Comment by dianabarsan** [comment] 2020-07-27 07:30
> We could use a different change detection for text doc
The problem with this approach is that deployments can update their `attachments/compressible_types` to include other file types we use, like `application/xml`. 

I think the correct way it to query `/_node/<nodename>/_config/attachments` and get the compressible types and the compression level, and use these values to generate the right md5.

**Comment by latin-panda** [comment] 2020-08-06 08:55
FYI: There is a [refactor in resources](https://github.com/medic/medic-conf/pull/340) waiting for AT. But this issue might still be there as I can see in the code that checks for changes [here](https://github.com/medic/medic-conf/blob/d97378419c4183a9dadf39b1d04cfc3348484bbe/src/lib/upload-configuration-docs.js#L42)

**Comment by dianabarsan** [comment] 2020-08-07 05:26
@njogz have been doing some back and fourth about him not being able to obtain the same digest when using zlib.gzip with the correct level of compression. 

It turns out that `zlib.gzip` in OSX is inconsistent with results compared to other operating systems, and is also inconsistent with the gzip implementation that CouchDB uses. 

https://github.com/nodejs/node/issues/12244

**Comment by dianabarsan** [comment] 2020-08-07 05:34
I think we need a different approach then, possibly similar to what @garethbowen suggested above.

> We could use a different change detection for text docs which downloads the actual attachment rather than relying on the md5.

If the attachment is of a `compressible_type`, don't rely on comparing digests and compare attachment content directly.

**Comment by njogz** [comment] 2020-08-31 06:33
Ready for AT on `345-inaccurate-overwrite-warning`

**Comment by dianabarsan** [comment] 2020-08-31 06:35
The issue also has a `cht-core` component that should be AT-ed on `add-db-config-get-endpoint`. 
Please, AT the `medic-conf` change against `cht-core` master **and** against the feature branch.

**Comment by newtewt** [comment] 2020-09-14 18:51
I've confirmed this working with both master and the branch detailed here. 

I've tried a few different combos of overwriting and uploading. Along with the steps outlined above. @njogz  feel free to close this out.

**Comment by garethbowen** [comment] 2021-01-10 22:45
@njogz Can this issue be closed now?

**Comment by njogz** [comment] 2021-01-11 18:35
@garethbowen yes it can be closed.

**Closed** 2021-01-11 18:45 UTC
Labels: Priority: 3 - Low, Type: Bug
