### ISSUE TITLE
upload-app-forms is not working. 

### ISSUE THREAD

**Issue by newtewt** [medic/medic-conf#187] opened 2019-05-09 14:16 UTC
When running command `medic-conf --url=https://<user>:<pass>@localhost upload-app-forms` nothing is being uploaded. This is because we changed how the extraArgs are separated in `medic-conf.js` and now the code in `upload-forms.js` is filtering all the forms out. 

Reproduce.
Have an empty webapp with no forms
Navigate to standard conf directory in webapp
Run medic-conf `upload-app-forms`
No forms are uploaded to the isntance.

**Comment by kennsippell** [comment] 2019-05-09 16:27
Dupe of #185

**Closed by kennsippell** 2019-05-09 16:27 UTC
