### ISSUE TITLE
Allow configuring of whitelabelling options

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-conf#167] opened 2019-03-26 23:46 UTC
We added a feature in 3.4.0 to allow for configuration of the app logo, favicon, title, and to add partner icons to the About page. These are configurable through the admin app but we should make sure these can be stored in the configuration structure and uploaded by medic-conf with the rest of the settings.

Also update the configuration documentation here: https://github.com/medic/medic-docs/blob/master/configuration/developing-community-health-applications.md#graphics

Feature issues: https://github.com/medic/medic/issues/4849 and https://github.com/medic/medic/issues/4850

**Comment by garethbowen** [comment] 2019-06-18 22:51
Blocked waiting for this to be merged: https://github.com/medic/medic-conf/pull/196

**Comment by garethbowen** [comment] 2019-12-02 22:40
Not yet started - delaying to 3.9.0

**Comment by latin-panda** [comment] 2020-07-09 12:38
Hi @garethbowen, The ticket says to update the documentation, but I remember it got moved to CHT community. Should I update both places?

**Comment by garethbowen** [comment] 2020-07-09 21:01
Good question! medic-docs is archived and will be deleted at some point, so you don't need to update it. Just update the cht-docs version, thanks!

**Comment by garethbowen** [comment] 2020-07-15 03:13
Ready for AT in `167-upload-branding`

**Comment by garethbowen** [comment] 2020-07-15 18:00
Ready for AT in `167-upload-branding`. Documentation change here: https://github.com/medic/cht-docs/pull/234

**Comment by newtewt** [comment] 2020-09-10 18:32
This is working as intended but there are some side affects coming from this.  

If I upload an image using medic-conf to partners. Then remove that partner from the `partners.json` and upload again. The attachment still lives in the doc in couchdb. It doesn't get displayed in the app in partners config or about page. However, looking at the network calls we are still sending that image just not rendering it.

**Comment by latin-panda** [comment] 2020-09-14 11:21
Hi @newtewt, I have updated the PR :) 
Regarding # 1: This issue currently exists in master. I added a filter to check and discard attachments that aren't mentioned in the settings json. Since this is a common functionally, the affected actions are: `upload-branding`, `upload-partners` and `upload-resources` only.

Regarding # 2: This issue could potentially be side effect of the [PR on attachments feature](https://github.com/medic/medic-conf/pull/336/files) for files that aren't image or json, but json files were accepted since before probably as part of another action (?). Gareth advices to take this one as part of another ticket, then we can identify the related actions commands and come up with a solution :)

**Comment by newtewt** [comment] 2020-09-14 13:36
Cool @latin-panda, I've reviewed after these new changes. I think we can close this one out. 

Confirmed that uploading branding and partners logos is possible via medic-conf. Confirmed it still works via the admin page.  Validated that removing partners and branding now removes from the attachment doc.

**Closed** 2020-09-14 21:58 UTC
Labels: Help wanted, Type: Improvement

**Comment by latin-panda** [comment] 2020-09-14 22:54
@newtewt I have added an issue for # 2: https://github.com/medic/medic-conf/issues/364 👍
