### ISSUE TITLE
Add a command line flag to accept all prompts to enable scripted execution

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#307] opened 2020-03-31 00:34 UTC
Scripts that use medic-conf to automate deployments hang waiting on the following input:

`We can't determine if you're going to overwrite someone else's changes or not. Would you like to proceed? [y/n]:`

This experience is great when there is a user present but for automated scripts (travis, CI pipelines, etc) medic-conf should support an option to `--force` the deployment and `--unattended` exit with an error isntead of prompting the user.

One example is LG's CI pipeline. This experience is incompatible with their pipeline and will effectively block their upgrade to 3.8.1 since medic-conf 3.1 is required to work with that version of the core.

**Comment by newtewt** [comment] 2020-07-15 15:27
For AT: medic-conf has a `--force` argument now that bypasses user input. Test that using the normal user input works `y`, `n`, `1`,`2`,`3` options and test that passing `--force` makes medic-conf upload docs, forms, creates-users,  move-contacts, overwrites changes without further prompting.

**Comment by garethbowen** [comment] 2020-07-15 18:32
This isn't a bug because the code is working as intended. Added to 3.11.0 and assigned to Nick because he's already working on it.

**Comment by ngaruko** [comment] 2020-07-21 07:40
Looks good with the `y/n` prompt. However, with the other prompt [1,2,3], there are instances where the prompt appears twice. In that case, only the first one is overridden by `--force`, the second prompt still appears and requires manual input. Did you wanna have a second look @newtewt ?
```
node ~/Medic/medic-dev/medic-conf/src/bin/medic-conf.js --local upload-app-forms --force
INFO Using local url from COUCH_URL environment variable: http://admin:****@localhost:5984/medic 
INFO Processing config in default. 
INFO Actions:
     - upload-app-forms 
INFO Starting action: upload-app-forms… 
INFO Preparing form for upload: death_report.xml… 
INFO No media directory found at /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/death_report-media for form /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/death_report.xml 
INFO Preparing form for upload: delivery.xml… 
INFO No media directory found at /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/delivery-media for form /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/delivery.xml 
INFO Preparing form for upload: pnc_danger_sign_follow_up_baby.xml… 
INFO No media directory found at /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/pnc_danger_sign_follow_up_baby-media for form /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/pnc_danger_sign_follow_up_baby.xml 
INFO Preparing form for upload: pnc_danger_sign_follow_up_mother.xml… 
INFO No media directory found at /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/pnc_danger_sign_follow_up_mother-media for form /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/pnc_danger_sign_follow_up_mother.xml 
INFO Preparing form for upload: pregnancy.xml… 
INFO No media directory found at /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/pregnancy-media for form /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/pregnancy.xml 
INFO Preparing form for upload: pregnancy_danger_sign.xml… 
INFO No media directory found at /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/pregnancy_danger_sign-media for form /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/pregnancy_danger_sign.xml 
INFO Preparing form for upload: pregnancy_danger_sign_follow_up.xml… 
INFO No media directory found at /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/pregnancy_danger_sign_follow_up-media for form /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/pregnancy_danger_sign_follow_up.xml 
INFO Preparing form for upload: pregnancy_facility_visit_reminder.xml… 
INFO No media directory found at /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/pregnancy_facility_visit_reminder-media for form /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/pregnancy_facility_visit_reminder.xml 
INFO Preparing form for upload: pregnancy_home_visit.xml… 
INFO No media directory found at /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/pregnancy_home_visit-media for form /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/pregnancy_home_visit.xml 
INFO Preparing form for upload: undo_death_report.xml… 
INFO No media directory found at /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/undo_death_report-media for form /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/undo_death_report.xml 
INFO Form /Users/bede/Medic/medic-dev/cht-core/config/default/forms/app/death_report.xml not uploaded, no changes 

[1] Overwrite the changes
[2] Abort so that you can update the configuration
[3] View diff

You are trying to modify a configuration that has been modified since your last upload. Do you want to? [1, 2, 3]: 

```

**Comment by newtewt** [comment] 2020-07-21 13:16
@ngaruko  I'm struggling to reproduce this. Can you provide more detail about how your setup and what state your instance was in?

**Comment by ngaruko** [comment] 2020-07-22 00:35
@newtewt Will put detail on that. Also was reported [here](https://github.com/medic/medic-conf/issues/113#issuecomment-558440722) with #113

**Comment by ngaruko** [comment] 2020-07-22 21:47
Couldn't replicate. I guess we can close it off - assume I made a mistake and tested while still on `master` . Then we will catch it in automation, if it occurs!

**Closed** 2020-07-23 12:42 UTC
Labels: Type: Feature
