### ISSUE TITLE
Improve DB usage for Forms uploader

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-conf#65] opened 2018-05-02 10:36 UTC
# Room for improvement

## Don't delete forms before uploading new ones
This is really helpful...sometimes!  

## Only upload docs that have changed
Often the forms do not change, but with the current practice of deleting everything and then uploading everything, we create extra, unnecessary changes.

## Consider using pouch's bulkDocs in place of put/post
`bulkDocs()` may have significant performance improvements for changes feed processing on the couch server-side, so long-term when uploading e.g. forms repeatedly.

# Approach

Replace forms-upload and forms-download functions with a syncrhonise-forms function - this should backup and remove unwanted forms on the server, and upload any new or changed forms, but leave others intact.

**Comment by kennsippell** [comment] 2020-03-13 19:25
Duplicate of https://github.com/medic/medic-conf/issues/271

**Closed by kennsippell** 2020-03-13 19:25 UTC
Labels: Type: Improvement, Won't fix: Duplicate
