### ISSUE TITLE
Validate xforms before uploading

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-conf#331] opened 2020-06-02 23:45 UTC
When uploading xform xml we assume the xslt transform will succeed. If for some reason the xml is not valid according to the xslt on the server API will error on boot and refuse to start. This is particularly bad because then medic-conf can't fix the problem because API is unavailable.

1. Add a new endpoint to the api service to do a test run of the xslt transform.
2. Modify medic-conf to call that endpoint before updating the doc so that errors are caught early. If the endpoint doesn't exist then attempt to update the doc, ie: fallback to the current process.
3. Improve the logging so the API log and the medic-conf CLI provide as much information as possible about how to fix the error.

**Comment by garethbowen** [comment] 2020-07-29 01:43
This keeps happening and is incredibly destructive causing an outage when it does so I'm scheduling this for 3.11.0.

**Comment by mrsarm** [comment] 2021-03-02 18:41
**Ready for AT.**

In order to test the solution both **medic-conf** and **cht-core** have a branch named `331-validate-xforms` with the changes, there is also a branch with the same name in the cht-docs repo but just documentation, but the document addition may help to understand how to test the API change without testing it with medic-conf.

**Pull requests:**
- https://github.com/medic/medic-conf/pull/374
- https://github.com/medic/cht-core/pull/6947
- https://github.com/medic/cht-docs/pull/439

**The PRs also solve the following tickets:**
- https://github.com/medic/medic-conf/issues/375
- https://github.com/medic/cht-core/issues/6557

### Quick test

Using the configuration at `config/default` in the cht-core , edit the file `forms/contact/person-create.xlsx` changing the name of the first group to "submission":

![Screenshot from 2021-03-02 14-44-54](https://user-images.githubusercontent.com/1608415/109692621-82b9e180-7b67-11eb-8304-039b0c9cf0d5.png)

Then try to push the configuration with `medic-conf --local` as usual.

If you using the master version of both medic-conf and cht-core, the configuration will be uploaded without problems, but then if you restart the API the startup process will be aborted and the API wont be available until the data is restored to its previous configuration. The error in the log will look like:

```
2021-03-02 14:47:03 DEBUG: Generating html and xml model for enketo form "form:contact:person:create" 
2021-03-02 14:47:03 ERROR: Fatal error initialising medic-api 
2021-03-02 14:47:03 ERROR: Error: Error transforming xml. xsltproc returned code "0", and signal "null". xsltproc stderr output:
ERROR: Submissions element(s) not supported.

    at ChildProcess.<anonymous> (/projects/medic/cht-core/api/src/services/generate-xform.js:36:23)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  [stack]: 'Error: Error transforming xml. xsltproc returned code "0", and signal "null". xsltproc stderr output:\n' +
    'ERROR: Submissions element(s) not supported.\n' +
    '\n' +
    '    at ChildProcess.<anonymous> (/projects/medic/cht-core/api/src/services/generate-xform.js:36:23)\n' +
    '    at ChildProcess.emit (events.js:314:20)\n' +
    '    at maybeClose (internal/child_process.js:1021:16)\n' +
    '    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)',
  [message]: 'Error transforming xml. xsltproc returned code "0", and signal "null". xsltproc stderr output:\n' +
    'ERROR: Submissions element(s) not supported.\n'
}
```

Using the versions of the cht-core and medic-conf pointed in this ticket will prevent the configuration from loading into the CHT. The logs from medic-conf will look like:

```
INFO Starting action validations: upload-contact-forms… 
INFO Validating form: clinic-create.xml… 
INFO Validating form: clinic-edit.xml… 
INFO Validating form: district_hospital-create.xml… 
INFO Validating form: district_hospital-edit.xml… 
INFO Validating form: health_center-create.xml… 
INFO Validating form: health_center-edit.xml… 
INFO Validating form: person-create.xml… 
ERROR Form /projects/medic/cht-core/config/default/forms/contact/person-create.xml with errors, API validations response: Error transforming xml. xsltproc returned code "0", and signal "null". xsltproc stderr output:
ERROR: Submissions element(s) not supported.
 
INFO Validating form: person-edit.xml… 
ERROR upload-contact-forms validations complete with errors: One or more forms appears to have errors found by the API validation endpoint. 
ERROR Error: One or more action validations failed.
    at module.exports (/projects/medic/medic-conf/src/lib/main.js:212:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

And the logs from the API:

```
REQ 1ddf3cb3-ef04-477d-b961-d1d1ac56844a ::ffff:127.0.0.1 admin POST /api/v1/forms/validate HTTP/1.1
2021-03-02 15:02:52 ERROR: Error validating XForm - Error transforming xml. xsltproc returned code "0", and signal "null". xsltproc stderr output:
ERROR: Submissions element(s) not supported.
```

Restarting the API won't fail, and any other change in the form won't be reflected in the CHT because the new version with the error was not uploaded.

If the user only upgrades the CHT but not the medic-conf tool the error will continue to happen because the API only has the endpoint to check the XML form but the check is executed by medic-conf. If the user only upgrade the medic-conf tool, trying to upload the configuration also will produce the error, the only difference is that the medic-conf will try to validate the first XML against the API, and when the API respond back with a HTTP 404, medic-conf will log the following and won't try to validate any of the other XML form before push:

```
INFO Starting actions validations… 
INFO Starting action validations: upload-app-forms… 
INFO Validating form: death_report.xml… 
WARN Form validation endpoint not found in your version of CHT Core, no form will be checked before push
```

**Comment by newtewt** [comment] 2021-03-10 19:43
Webapp updated but not medic conf uploads fine.  Uploads a broken form as well. 
Webapp and medic-conf updated. There is some issues that need addressed in medic-conf.  I commented on the PR where I believe a change to how validations are ran is necessary. Running the default actions puts the validations before the corresponding execute happens. Meaning you could get into a situation where the current XML is fine but after converting it fails on the server because there is no follow up validation. 

The specific error looks good!
```
ERROR Form /home/newt/dev/cht-core/config/default/forms/contact/person-create.xml with errors, API validations response: Error transforming xml. xsltproc returned code "0", and signal "null". xsltproc stderr output:
ERROR: Submissions element(s) not supported
```
Works with the webapp/api being the older version and medic-conf having the check. 

One thought is that in cases where the check doesn't do anything(old api version) it still shows passed.  I wonder if it makes more sense to say it didn't run.

**Comment by mrsarm** [comment] 2021-04-06 14:04
@newtewt I fixed the issue you found, and as discussed earlier, I removed the "validation" phase (https://github.com/medic/medic-conf/issues/375) and now the validations are executed at the beginning of each action, so the changes won't prevent other actions to upload stuff if one action fails, but will prevent the upload of invalid XForms.

I also added the validations in the _"App Management" > "App forms"_ view (check https://github.com/medic/cht-core/issues/6557#issuecomment-808323304), and addressed the suggestions from Diana [here](https://github.com/medic/cht-core/pull/6947#discussion_r603031716).

**Comment by ngaruko** [comment] 2021-04-07 02:34
LGTM
Tested in collaboration with @brad1905 on local installs (both cht-core and medic-conf). On `master`, uploading error form gets successful but restarting API hangs with errors;
![image](https://user-images.githubusercontent.com/6979995/113801937-ee6a1c80-97ad-11eb-8022-5b575a2de40e.png)
Using branches, form not uploaded , error in medic-conf CLI:
![image](https://user-images.githubusercontent.com/6979995/113802044-1eb1bb00-97ae-11eb-8f50-5ce0d8fe666b.png)
 and in API
![image](https://user-images.githubusercontent.com/6979995/113802086-2ec99a80-97ae-11eb-8c9b-119f053862ef.png)
and restarting the API works atm.

**Comment by ngaruko** [comment] 2021-04-07 03:06
Also tested a few combination: 

1. `medic-conf master` vs `cht-core/331-validate-xforms` behaves same `master/master` (ie upload successful, but API will not restart - if stopped). (OK)
2.  `cht-core master` vs `medic-conf/331-validate-xforms` - This one looks buggy @mrsarm. I throws errors in medic-conf CLI for some forms:
```
INFO Preparing form for upload: clinic-create.xml… 
INFO No media directory found at /Users/bede/tests/cht-core/config/default/forms/contact/clinic-create-media for form /Users/bede/tests/cht-core/config/default/forms/contact/clinic-create.xml 
ERROR Error: Unable to fetch xml attachment of doc with id form:contact:clinic:create, returned status code = undefined
    at Object.preUploadForm (/Users/bede/Medic/medic-dev/medic-conf/src/lib/warn-upload-overwrite.js:221:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (/Users/bede/Medic/medic-dev/medic-conf/src/lib/upload-forms.js:63:21)
    at async module.exports (/Users/bede/Medic/medic-dev/medic-conf/src/lib/main.js:204:5)
    at async /Users/bede/Medic/medic-dev/medic-conf/src/bin/medic-conf.js:11:18 
```

and kills the API at once, with errors:
```
2021-04-07 03:00:10 ERROR: Server error: '{"errno":-54,"code":"ECONNRESET","syscall":"read"}' 
2021-04-07 03:00:10 ERROR: UNCAUGHT EXCEPTION! 
2021-04-07 03:00:10 ERROR:   Error: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_http_outgoing.js:668:15)
    at ServerResponse.end (_http_outgoing.js:789:7)
    at ServerResponse.end (/Users/bede/tests/cht-core/api/node_modules/compression/index.js:107:21)
    at respond (/Users/bede/tests/cht-core/api/src/server-utils.js:33:7)
    at Object.serverError (/Users/bede/tests/cht-core/api/src/server-utils.js:104:5)
    at ProxyServer.<anonymous> (/Users/bede/tests/cht-core/api/src/routing.js:720:15)
    at ProxyServer.emit (/Users/bede/tests/cht-core/api/node_modules/eventemitter3/index.js:210:27)
    at ClientRequest.proxyError (/Users/bede/tests/cht-core/api/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:165:18)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9) {
  [stack]: 'Error [ERR_STREAM_WRITE_AFTER_END]: write after end\n' +
    '    at writeAfterEnd (_http_outgoing.js:668:15)\n' +
    '    at ServerResponse.end (_http_outgoing.js:789:7)\n' +
    '    at ServerResponse.end (/Users/bede/tests/cht-core/api/node_modules/compression/index.js:107:21)\n' +
    '    at respond (/Users/bede/tests/cht-core/api/src/server-utils.js:33:7)\n' +
    '    at Object.serverError (/Users/bede/tests/cht-core/api/src/server-utils.js:104:5)\n' +
    '    at ProxyServer.<anonymous> (/Users/bede/tests/cht-core/api/src/routing.js:720:15)\n' +
    '    at ProxyServer.emit (/Users/bede/tests/cht-core/api/node_modules/eventemitter3/index.js:210:27)\n' +
    '    at ClientRequest.proxyError (/Users/bede/tests/cht-core/api/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:165:18)\n' +
    '    at ClientRequest.emit (events.js:315:20)\n' +
    '    at Socket.socketErrorListener (_http_client.js:469:9)',
  [message]: 'write after end',
  code: 'ERR_STREAM_WRITE_AFTER_END',
  [Symbol(kEnhanceStackBeforeInspector)]: [Function: bound enhanceStackTrace] {
    [length]: 0,
    [name]: 'bound enhanceStackTrace'
  }
} 
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by mrsarm** [comment] 2021-04-07 18:29
@ngaruko the `ECONNRESET` error is a connection error, not saying that is not a bug from the PR but maybe you have had a connection issue? was medic-conf or cht in a remote location? I couldn't reproduce your bug, I have checked out the latest master version of the CHT and used the medic-conf version developed for this ticket but without issues like you pointed out.

What config repo did you use? maybe I can test with the same repo. Also did you modified the forms in some way that I can reproduce?

**Comment by ngaruko** [comment] 2021-04-08 00:08
@mrsarm . I think the culprit is around this [`/api/v1/forms/validate` endpoint](https://github.com/medic/medic-conf/blob/331-validate-xforms/src/lib/api.js#L124). If that endpoint does not exist, which is the case for `master`, it tends to crash the API. Tried that with a random endpoint and got same results, but existing endpoints work fine.

**Comment by ngaruko** [comment] 2021-04-08 06:16
think the bug, if any, is in our API. Happens if I POST same form to a fake endpoint from a different client, on master. Nothing to do with medic-conf or this PR IMO. I have raised a [different issue](https://github.com/medic/cht-core/issues/7056).

**Comment by ngaruko** [comment] 2021-04-09 00:00
Since we weren't able to reproduce and that it happened in a local couchdb install (instead of docker couchdb as recommended in [development setup](https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md#couchdb-on-docker), we decided to ignore it and move on with the release - Feel free to merge @mrsarm

**Closed** 2021-04-12 14:40 UTC
Labels: Priority: 2 - Medium, Type: Bug
